services:
  postgres:
    image: postgres:16
    container_name: postgres16
    restart: always

    environment:
      POSTGRES_DB: cebraspe_pro
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  pgdata:
